### ISSUE TITLE
The client is not able to connect with the server.

### ISSUE THREAD

**Issue by kjawadDeveloper** [tollcafe/AIDLClient#1]
I downloaded both the repos and installed server and after that i run the client but client app crashed.

**Comment by Tornjk** [comment]
I experienced the same issue and had to add this to the clients manifest to fix it

`<queries>
        <package android:name="com.tollcafe.aidlserver"/>
    </queries>`

**Comment by yhm2046** [comment]
> <queries> <package android:name="com.tollcafe.aidlserver"/> </queries>

I add it to client still error:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tollcafe.aidlclient, PID: 18597
    java.lang.NullPointerException: Attempt to invoke interface method 'int com.tollcafe.aidlserver.IAIDLColorInterface.getColor()' on a null object reference
        at com.tollcafe.aidlclient.MainActivity$2.onClick(MainActivity.java:53)
        at android.view.View.performClick(View.java:7317)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7291)
        at android.view.View.access$3600(View.java:838)
        at android.view.View$PerformClick.run(View.java:28247)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
I/Process: Sending signal. PID: 18597 SIG: 9
`

my as is Android Studio Electric Eel, 2022.1.1 Patch 1, and test devices is android 10 and 11

**Comment by yhm2046** [comment]
> <queries> <package android:name="com.tollcafe.aidlserver"/> </queries>

I rebuild it successfull by myself, thanks Tornjk, you are right!
